// app/layout.js
import { Poppins, Preahvihear } from "next/font/google";
import "./globals.css";

// Poppins with multiple weights
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

// Preahvihear (only weight 400 available)
const preahvihear = Preahvihear({
  weight: [ "400"],
  subsets: ["latin"],
  variable: "--font-preahvihear",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${preahvihear.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
