// app/layout.js
import { Poppins, Preahvihear } from "next/font/google";
import "./globals.css";
import Navbar from "@/Layout/Navbar/Navbar";

// Poppins with multiple weights
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

// Preahvihear (only weight 400 available)
const preahvihear = Preahvihear({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-preahvihear",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${preahvihear.variable}`}>
      <body
        className={`antialiased
        w-full absolute top-0 z-[-2] 
        min-h-screen h-auto bg-[#11071f]`}
      >
        <div className="max-w-[1920px] min-h-[100vh] mx-auto px-4 md:px-[40px] lg:px-[120px] xl:px-[200px]">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
